version: '2.1'
services:

  localstack:
    image: localstack/localstack-full
    ports:
      - "4569:4569"
      - "8080:8080"
      - "4566:4566"
      - "4564:4564"
    environment:
      - SERVICES=dynamodb
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOTE_DOCKER=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - /var/run/docker.sock:/var/run/docker.sock